//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopOne.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class redshopDB : DbContext
    {
        public redshopDB()
            : base("name=redshopDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_attribute_values> tbl_attribute_values { get; set; }
        public virtual DbSet<tbl_attributes> tbl_attributes { get; set; }
        public virtual DbSet<tbl_images> tbl_images { get; set; }
        public virtual DbSet<tbl_invoice> tbl_invoice { get; set; }
        public virtual DbSet<tbl_product_attribute> tbl_product_attribute { get; set; }
        public virtual DbSet<tbl_products> tbl_products { get; set; }
        public virtual DbSet<tbl_users> tbl_users { get; set; }
        public virtual DbSet<tbl_indexcontents> tbl_indexcontents { get; set; }
        public virtual DbSet<View_comments> View_comments { get; set; }
        public virtual DbSet<View_product_attribute> View_product_attribute { get; set; }
        public virtual DbSet<tbl_comments> tbl_comments { get; set; }
        public virtual DbSet<tbl_pictures> tbl_pictures { get; set; }
    }
}
