//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_images
    {
        public int pkId { get; set; }
        public int FKproduct_ID { get; set; }
        public string banerphoto { get; set; }
        public string smallphoto { get; set; }
        public string photo_1 { get; set; }
        public string photo_2 { get; set; }
        public string photo_3 { get; set; }
        public string photo_4 { get; set; }
        public string photo_5 { get; set; }
        public string photo_6 { get; set; }
    
        public virtual tbl_products tbl_products { get; set; }
    }
}
