//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pictures
    {
        public int pkID { get; set; }
        public int FKproductID { get; set; }
        public string PicSrc { get; set; }
        public bool MainPic { get; set; }
    
        public virtual tbl_products tbl_products { get; set; }
    }
}
