//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_attributes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_attributes()
        {
            this.tbl_attribute_values = new HashSet<tbl_attribute_values>();
            this.tbl_product_attribute = new HashSet<tbl_product_attribute>();
        }
    
        public int pkID { get; set; }
        public string attribute_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_attribute_values> tbl_attribute_values { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_product_attribute> tbl_product_attribute { get; set; }
    }
}
