//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_comments
    {
        public int pkId { get; set; }
        public Nullable<int> fkUserID { get; set; }
        public int fkproductID { get; set; }
        public System.DateTime time { get; set; }
        public bool status { get; set; }
        public int Score { get; set; }
        public string Messages { get; set; }
        public string Name { get; set; }
        public string email { get; set; }
        public bool deleted { get; set; }
    
        public virtual tbl_products tbl_products { get; set; }
        public virtual tbl_users tbl_users { get; set; }
    }
}
