//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invoice
    {
        public int pkID { get; set; }
        public long invoice_num { get; set; }
        public int fkProduct_id { get; set; }
        public long productPrice { get; set; }
        public Nullable<int> fkUser_id { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string PostalCode { get; set; }
        public string orderFname { get; set; }
        public string orderLname { get; set; }
        public string orderPhoneNum { get; set; }
        public string transID { get; set; }
        public bool transStatus { get; set; }
        public int fkOrderStatus_id { get; set; }
        public string TrackingCode { get; set; }
        public bool Registered { get; set; }
    
        public virtual tbl_products tbl_products { get; set; }
        public virtual tbl_users tbl_users { get; set; }
    }
}
