//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_indexcontents
    {
        public int pkID { get; set; }
        public string ContentsName { get; set; }
        public string ContentsValue { get; set; }
        public string Description { get; set; }
    }
}
