//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_product_attribute
    {
        public int pkID { get; set; }
        public string pName { get; set; }
        public int sku { get; set; }
        public string description { get; set; }
        public long price { get; set; }
        public System.DateTime createTime { get; set; }
        public bool active { get; set; }
        public string HID { get; set; }
        public int FKproduct_ID { get; set; }
        public int FKattribute_ID { get; set; }
        public int FKvalue_ID { get; set; }
        public string attribute_name { get; set; }
        public string value { get; set; }
        public Nullable<decimal> discount { get; set; }
    }
}
